### ISSUE TITLE
*Bedingungslos*

### ISSUE THREAD

**Issue by AssertionBit** [AssertionBit/OsspitaUI#2]
### TL;TR

Will need to remove all elements related to Zustand. This will remove all problems, connected to strange, non-required OOP magic in JS/TS.

### TODO

- [ ] Move all services to `rtk` format.
- [ ] Expose all internal models and states as interfaces.
- [ ] Move all *external* fetching services to `rtk` format.
- [ ] Bring all this back to application.
